### ISSUE TITLE
Invalid timestamps on iOS

### ISSUE THREAD

**Issue by perqa** [googlevr/webvr-polyfill#201] opened 2017-03-09 12:40 UTC
On iOS (using Cordova webview), the console is flooded with the message 

> Invalid timestamps detected. Time step between successive gyroscope sensor samples is very small or not monotonic

Rows 5703 and onwards:

```    
                var deltaS = timestampS - this.previousTimestampS;
                if (deltaS <= Util.MIN_TIMESTEP || deltaS > Util.MAX_TIMESTEP) {
                    console.warn('Invalid timestamps detected. Time step between successive ' +
                    'gyroscope sensor samples is very small or not monotonic');
                    this.previousTimestampS = timestampS;
                    return;
                }
```

This probably means the timestamps are invalid, or at least not changing with time...

**Comment by jsantell** [comment] 2017-05-23 22:09
I don't have an iOS device handy (maybe a Cordova webview thing as well?), but do you know if the timestamps are not being updated, or if the delta between them are too small? iOS + Cordova could be an edge case and may need more data on what these values are

**Comment by dirtybluejeans** [comment] 2017-08-10 17:50
I'm also experiencing the exact same symptoms. The code works fine when opened in Safari, and the webvr controls appear nice and the head tracking also works. However, inside cordova there's a barrage of errors about invalid timestamps. Head-tracking still works though I'm guessing the predictive filter would be broken.

**Comment by jsantell** [comment] 2018-01-03 23:52
Fixed in https://github.com/googlevr/cardboard-vr-display/pull/9 -- will be in the next polyfill release

**Closed** 2018-01-03 23:52 UTC
Labels: bug, iOS

**Comment by zaherkassem** [comment] 2018-07-23 11:17
any news on this issue? when will next polyfill release be ready?

**Comment by jsantell** [comment] 2018-07-23 20:59
The latest versions of webvr polyfill contain this fix, anything [v0.10.3](https://github.com/immersive-web/webvr-polyfill/releases/tag/v0.10.3) and up as far as I can tell

**Comment by lijualivenow** [comment] 2020-06-18 09:51
I am working with the 8th wall and aframe. I am using <a-scene embedded> for displaying UI. It is working perfectly in Android but it showing the loading page on iPhone Safari.
Following error is getting
webvr-polyfill: Invalid timestamps detected: Timestamp from devicemotion outside expected range.

**Comment by jsantell** [comment] 2020-06-19 22:46
iOS reports timestamps out of order sometimes, that's on Safari, but should still work. I suspect an issue with 8th wall or aframe

**Comment by cheitovilla** [comment] 2020-09-17 04:40
any solution? i'm using 8thwall and i have the same problem! please help!

**Comment by vin-ni** [comment] 2020-11-11 09:55
Any news on this?

**Comment by jsantell** [comment] 2020-11-11 18:37
Might be worthwhile making a new issue for 8th wall specifically with a reproducible case for others; invalid timestamps are a byproduct of iOS's devicemotion implementation and not necessarily related to any 8th wall issues

**Comment by kotavy** [comment] 2021-02-15 14:50
> The latest versions of webvr polyfill contain this fix, anything [v0.10.3](https://github.com/immersive-web/webvr-polyfill/releases/tag/v0.10.3) and up as far as I can tell

I also ran into this warning when using 8th Wall. After inspecting the A-Frame dist, the dependency is `"webvr-polyfill": "^0.10.12"` on A-Frame v1.2.0 released 11 days ago (and at least 1.1.0 before that for 8frame-1.1.0 users). 8th Wall uses a fork of the A-Frame dist and the same `^0.10.12` dependency is carried over.

I don't have more information since the warning should be resolved past `0.10.3`, but this would point towards A-Frame over 8th Wall for those looking to open issues with these specific frameworks.

**Comment by lijualivenow** [comment] 2021-02-16 05:59
Hi @kotavy,
for the 8th wall please include the following codes in **head.html**.

<meta name="8thwall:renderer" content="aframe:1.1.0">


<script crossorigin="anonymous" src="https://cdn.jsdelivr.net/gh/donmccurdy/aframe-extras@v6.1.1/dist/aframe-extras.min.js"></script>

**Comment by StudioNopqrst** [comment] 2022-03-03 11:37
I am testing a project using aframe. Tried both 8th Wall and Mindar.js build, they both do the same crashes and give the same polyfill error and invalid timestamps on an iPhone13Pro iOS 15.3.1 Safari. the same does not happen on an old iPhone 6s iOS 14.4.2. 

Is there a way we can make sure Aframe or 8thWall the tracking code will use our designated version of polyfill?

Thanks.
