### ISSUE TITLE
Webkit workaround doesn't work if VR mode is enabled when the phone is in landscape orientation

### ISSUE THREAD

**Issue by dmarcos** [googlevr/webvr-polyfill#140] opened 2016-08-07 19:31 UTC
I feel your pain. I spent a lot of time chasing these issues as well in `a-frame`. If I enter VR mode in landscape orientation this is what I get with the basic example and using the `master` branch (v0.9.15 is also affected) on an iPhone 6 Plus ![landscape](https://d3vv6lp55qjaqc.cloudfront.net/items/3R0a1k3B2v003C0R3A47/Image%202016-08-04%20at%2012.57.40%20PM.png?v=958d8255)

I don't have a solution for this particular glitch yet. I tried calling `Util.safariCssSizeWorkaround` in multiple parts and never got to resize the canvas appropriately. Only switching to portrait and back to landscape forces the canvas to the correct size.

**Comment by borismus** [comment] 2016-08-16 02:02
Argh. Is this an iPhone specific thing? I've seen variations on this theme, and it's a tough one to squish.

Have you had success in your workarounds?

**Comment by dmarcos** [comment] 2016-08-16 12:08
Yes the problem is iphone specific. It's a manifestation of https://bugs.webkit.org/show_bug.cgi?id=152556
I hope it gets fixed in iOS 10.

**Comment by dmarcos** [comment] 2016-08-17 00:55
We found out playing with `BUFFER_SCALE` that setting it to `1 / window.devicePixelRatio` makes the trick because the canvas will have the screen size (not physical size) and does not need to be resized. The problem is that the resolution is very low.

**Comment by borismus** [comment] 2016-09-01 18:34
Yeah, this doesn't seem like a good workaround to me. Aiming to wait a bit to see how it is in iOS 10.

**Comment by jsantell** [comment] 2017-12-28 16:49
This looks like it's fixed in iOS10+, haven't reproduced this on any of those devices. With iOS11 rolling out, we're looking at a much smaller chunk of iOS9 devices moving forward. Closing this, please reopen if there's a use case I'm misunderstanding!

**Closed by jsantell** 2017-12-28 16:49 UTC
Labels: bug, iOS
